- hosts: newservers
  become: True
  become_method: sudo

  tasks: 
  - name: adduser to groups
    ansible.builtin.user:
      name: admin
      groups:
        - wheel
        - docker
      append: yes
  - name: Reboot the machine
    ansible.builtin.reboot:
        