- hosts: newservers
  become: True
  become_method: sudo
  
  tasks:
  - name: Install Cloudwatch Agent
    ansible.builtin.package:
      name: amazon-cloudwatch-agent
      state: present
  - name: Start The Agent
    ansible.builtin.service:
      name: amazon-cloudwatch-agent
      state: started
  - name: Restart the Agent
    ansible.builtin.service:
      name: amazon-cloudwatch-agent
      state: restarted